### ISSUE TITLE
Review #1 - No se pueden hacer peticiones a la API.

### ISSUE THREAD

**Issue by FacundoEG** [parodimatias/rock-scissor-paper#1]
Hola Mati! como andas? te mando felicitaciones por haber enviado el desafío del modulo 6!

Para empezar te queria señalar unas cosita, fijate que quise entrar a la docu de la app en postman y al parecer no estaría siendo publica, ya que no me permite ingresar: 

![image](https://user-images.githubusercontent.com/79592789/146810048-cbb1ad8c-3d1d-407d-bb49-eb7bbeabfded.png)

Segundo, te comento que cuando quiero ingresar a crear una sala recibo un error del metodo POST de esa page:

![image](https://user-images.githubusercontent.com/79592789/146811708-0cafe065-9842-43da-8bde-af7f45e7ca17.png)

Por lo que estuve viendo, la API_BASE_URL que esta en state.ts apunta para el localhost.

Te recomendaría que modifiques eso para que apunte al host de Heroku (`https://mp-rock-scissor-paper.herokuapp.com`) . 

![image](https://user-images.githubusercontent.com/79592789/146811974-0a486a13-d6e0-4025-a925-781ab2146063.png)

Asi que si podes Mati fijate de cambiar esas dos cositas, mas que nada lo de la URL asi podemos probar el juego.

Saludos!

**Comment by parodimatias** [comment]
Facu, cambios realizados. 

A mi me andaba bien en heroku pero era porque tenia el server todavia corriendo en mi pc jaja!

Gracias por mirarlo
